import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from langchain_core.messages import HumanMessage,AIMessage
from models.schema import AgentSchema,JudgeSchema
from langgraph.graph import StateGraph,START,END
from dotenv import load_dotenv
load_dotenv()



from utils.llm_pick import pick_llm
from utils.database import DatabaseUtil


# AI Agent Code

def curate_ques(state: AgentSchema) -> AgentSchema:
    user_ques = state.user_ques  # why state.user_ques not state['user_ques'] as this is a pydantic object not a dictionary
    llm = pick_llm("low")
    
    response = llm.invoke(f"""
    Rewrite the following user question to make it clear and grammatically correct.

    Do not change its meaning.
    Return only the rewritten question.
    Do not provide explanations, multiple versions, examples, or SQL.

    Question: {user_ques}
    """)

    state.curated_ques = response.text  # updating the state
    state.messages = state.messages + [HumanMessage(content=response.text)] # appened the curated question to the messages list
    return state
    
def prompt_query_context(state: AgentSchema) -> AgentSchema:
    curated_question = state.curated_ques
    conn_details = {
        "host": os.getenv("host"),
        "port": os.getenv("port"),
        "user": os.getenv("user"),
        "password": os.getenv("password"),
        "dbname": os.getenv("database")
    }
    obj = DatabaseUtil(conn_details)
    
    schema_info = obj.schema_details("public")
    
    prompt = f"""
    You are an SQL analyst agent. Your task is to convert the user's natural language 
    query into Postgres SQL query that can be executed on the database. You are provided 
    with the user's original query and the schema details of the database, including
    table names, column names, data types, and sample data for each table so that 
    you can understand the structure of the database and generate an accurate SQL query.
    Unless user explicitly asks for specific number of rows, always limit the output to 10 rows.
    Note - Just generate the SQL query without any explanation or additional text because
    this query will be executed directly on the database. So, the output should be SQL
    ready to be executed without any modifications.  
    
    User's Original Query: {curated_question}

    Database Schema Details:
    {schema_info}
    
    """    

    state.prompt_query_context = prompt

    return state

# Generate SQL Query Node
def generate_sql(state: AgentSchema) -> AgentSchema:

    prompt = state.prompt_query_context

    llm = pick_llm("high")

    generated_sql_query = llm.invoke(prompt).text

    # Remove markdown SQL code fences if generated by LLM
    generated_sql_query = generated_sql_query.replace("```sql", "")
    generated_sql_query = generated_sql_query.replace("```", "")
    generated_sql_query = generated_sql_query.strip()

    state.generated_sql_query = generated_sql_query

    return state


def is_safe_sql(state: AgentSchema) -> AgentSchema:

    sql_query = state.generated_sql_query

    llm = pick_llm("high")  
    llm_judge = llm.with_structured_output(JudgeSchema)

    prompt = f"""
    You are an SQL Judge for data security. Your task is to determine whether the SQL query is 
    safe or not. The SQL query should only be used for data retrieval and should not modify the 
    database in any way. Neither the SQL query nor the prompt should contain any SQL commands that can modify the
    database, such as INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE, or any other commands that can change
    the structure or content of the database. If the SQL query is safe, respond with 'Yes' otherwise respond with 
    'No'. Additionally, provide comments explaining your decision.
    Here's the SQL query to evaluate:
    {sql_query}"""

    response = llm_judge.invoke(prompt).model_dump()  # Get the structured output as a dictionary
    state.is_safe = response['answer']
    state.comments = response['comments']

    return state

def cancelled_SQL_node(state: AgentSchema) -> AgentSchema:
    comments = state.comments
    state.final_answer = f"The Generated SQL query is unsafe to execute. The reason provided by the judge is {comments}. Therefore the SQL query will not be executed."
    state.messages = state.messages+[AIMessage(content=state.final_answer)]
    return state

def execute_SQL(state: AgentSchema) -> AgentSchema:
    sql_query = state.generated_sql_query
    
    conn_details = {
    "host": os.getenv("host"),
    "port": os.getenv("port"),
    "user": os.getenv("user"),
    "password": os.getenv("password"),
    "dbname": os.getenv("database")
    }
    obj = DatabaseUtil(conn_details)
    structured = obj.execute_sql_structured(sql_query)  # execute the sql query from the database

    if structured["success"]:
        state.sql_query_execution_result = str([tuple(row) for row in structured["rows"]])
        state.result_columns = structured["columns"]
        state.result_rows = structured["rows"]
    else:
        state.sql_query_execution_result = structured["error"]
        state.result_columns = []
        state.result_rows = []

    return state

# represent the final answer node

def represent_final_answer(state: AgentSchema) -> AgentSchema:
    execution_result = state.sql_query_execution_result
    curated_question = state.curated_ques
    
    llm = pick_llm("low")
    prompt = f"""
    You are an SQL analyst agent. Your task is to provide a final answer to the user based on the
    execution result of the SQL query and the user's original question. The final answer should be
    concise, clear, and directly address the user's query. Avoid including any SQL code or technical
    details in the final answer. The final answer should be in a user-friendly format that is easy to
    understand. If the execution result is empty or does not provide a clear answer to the user's question, explain this in the final answer. \n
    Here is the execution result: {execution_result} \n
    Here is the user's original question: {curated_question}
    """
    
    llm_response = llm.invoke(prompt).text
    
    state.final_answer = llm_response
    state.messages = state.messages+[AIMessage(content=llm_response)]
    
    return state
    

#        GRAPH BUILDING

sql_agent_graph = StateGraph(AgentSchema)


# ALL NODES
sql_agent_graph.add_node("curate_ques",curate_ques)
sql_agent_graph.add_node("prompt_query_context",prompt_query_context)
sql_agent_graph.add_node("generate_sql",generate_sql)
sql_agent_graph.add_node("is_safe_sql",is_safe_sql)
sql_agent_graph.add_node("cancelled_sql",cancelled_SQL_node)
sql_agent_graph.add_node("execute_sql",execute_SQL)
sql_agent_graph.add_node("final_answer",represent_final_answer)

# CONNECTING ALL NODES THROUGH EDGES

sql_agent_graph.add_edge(START,"curate_ques")
sql_agent_graph.add_edge("curate_ques","prompt_query_context")
sql_agent_graph.add_edge("prompt_query_context","generate_sql")
sql_agent_graph.add_edge("generate_sql","is_safe_sql")


def is_safe_sql_edge(state: AgentSchema) -> str:
    is_safe = state.is_safe
    
    if(is_safe.lower()=="yes"):
        return "execute_sql"
    else:
        return "cancelled_sql"
    
sql_agent_graph.add_conditional_edges(
    "is_safe_sql",
    is_safe_sql_edge,
    {
        "execute_sql": "execute_sql",
        "cancelled_sql": "cancelled_sql"
    }
)

sql_agent_graph.add_edge("cancelled_sql",END)
sql_agent_graph.add_edge("execute_sql","final_answer")
sql_agent_graph.add_edge("final_answer",END)

# Compiled at import time so other modules (the router agent, the API layer)
# can just `from agents.sql_analyst import sql_analyst` instead of every
# caller re-compiling the graph itself.
sql_analyst = sql_agent_graph.compile()


if __name__=="__main__":
    SQL_analyst = sql_analyst
    
    input_schema = {
        "messages": [],
        "user_ques": "What are the different types of Payment Methods we have in our database",
        "curated_ques": "",
        "prompt_query_context": "",
        "generated_sql_query": "",
        "is_safe": "No",
        "comments": "",
        "sql_query_execution_result": "",
        "final_answer": ""
    }

    sql_analyst_response = SQL_analyst.invoke(input_schema)
    print(sql_analyst_response['messages'])  # prinitng the final response
    
    print("***********************************************")
    
    print(sql_analyst_response["generated_sql_query"])
    
    print("************************************************")
    
    print(sql_analyst_response["sql_query_execution_result"])
    

