from pydantic import BaseModel,Field
from typing import Annotated,Literal,Any,Optional
from operator import add

class AgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(...,description="List of messages to be processed by the agent")
    # messages will keep the chat history if we want fresh user_input everytime we can use a user_input as str in state
    # will be easy to extarct the user_input fromt it
    user_ques: str = Field(...,description="The original question asked by the user")
    curated_ques : str = Field(...,description="curated user question ")
    prompt_query_context : str = Field(...,description="a detailed prompt with databse context that will help agent to generate SQL query")
    generated_sql_query : str = Field(...,description="The SQL query generated by the agent based on the curated question and prompt context")
    is_safe : Literal["Yes","No"] = Field(...,description="Indicates whether the generated SQL query is safe to execute or not")
    comments : str = Field(...,description="comments regrading the safety of generated SQL query")
    sql_query_execution_result : str = Field(...,description="The result of executing the SQL query on the database")
    final_answer : str = Field(...,description="The final answer generated by the agent base on the SQL execution result and curated question")
    # --- Additive fields used by the API layer to render structured results in the UI.
    # Optional/defaulted so existing callers that don't set them keep working unchanged.
    result_columns : list = Field(default_factory=list, description="Column names of the SQL execution result, when available")
    result_rows : list = Field(default_factory=list, description="Row data of the SQL execution result as a list of lists, when available")
    execution_time_seconds : float = Field(default=0.0, description="Wall-clock time taken to run this agent, in seconds")

#   Judge schema is not a state it will be used for structured output generation in judge llm

class JudgeSchema(BaseModel):
    answer : Literal["Yes","No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments : str = Field(..., description="Additional comments or feedback from the judge regarding the SQL query")


# ---------------------------------------------------------------------------
# Router / top-level "Auto" agent schemas
# ---------------------------------------------------------------------------

class RouterSchema(BaseModel):
    answer : Literal["sql","etl"] = Field(
        ...,
        description="Which specialist agent should handle this request: 'sql' for questions that need to be answered "
                    "by querying the database, 'etl' for requests that involve extracting data from an external API, "
                    "cleaning/transforming it, and producing a dataset/file."
    )


class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(default_factory=list, description="Conversation messages")
    route_response : str = Field(default="", description="The route chosen by the router node: 'sql' or 'etl'")
    sql_result : Optional[dict] = Field(default=None, description="Full result dict returned by the SQL analyst, when routed to sql")
    etl_result : Optional[dict] = Field(default=None, description="Full result dict returned by the ETL analyst, when routed to etl")
    final_answer : str = Field(default="", description="The final natural-language answer surfaced to the user")


# ---------------------------------------------------------------------------
# ETL analyst schemas
# ---------------------------------------------------------------------------

class ETLPlanSchema(BaseModel):
    api_url : str = Field(..., description="The HTTP(S) API URL to extract data from, inferred from the user's request")
    output_filename : str = Field(..., description="A short, filesystem-safe filename ending in .csv for the resulting dataset")


class ETLAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(default_factory=list)
    user_request : str = Field(..., description="The user's original ETL request")
    api_url : str = Field(default="")
    output_filename : str = Field(default="")
    raw_record_count : int = Field(default=0)
    clean_record_count : int = Field(default=0)
    output_path : str = Field(default="")
    execution_time_seconds : float = Field(default=0.0)
    status : Literal["pending","success","failed"] = Field(default="pending")
    error : str = Field(default="")
    final_answer : str = Field(default="")
    # Intermediate data passed between extract -> transform -> load nodes.
    # Kept as plain lists of dicts (not a DataFrame) so the pydantic state stays
    # JSON-serializable; nodes rebuild a DataFrame from clean_records when needed.
    raw_records : list = Field(default_factory=list, exclude=True)
    clean_records : list = Field(default_factory=list, exclude=True)